# Generated by Django 5.1.5 on 2025-01-26 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DashApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('base_state', models.JSONField()),
                ('stateless_app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz_app.app')),
            ],
        ),
    ]
